### ISSUE TITLE
CoFiX Fee Revenue Allocation Program

### ISSUE THREAD

**Issue by cdcxzl** [Computable-Finance/CIPs#3]
cip:
title:CoFiX Fee Revenue Allocation Program（CoFiX手续费收入分配方案）
author:cofixfans(cdcxzl@qq.com)
vote:
discussion: https://github.com/Computable-Finance/CIPs/issues
status:PROPOSED
created:2020-11-21
CoFiX手续费收入分配方案
发起背景
当前手续费收入资金的分配方案，导致储蓄池的沉淀资金过多，每一笔手续费收入，都应该发挥他应有的作用，保障CoFi持有者的权益，所以发起此提案。
Abstract(摘要）
将手续费收入的资金分成三部分：1，锁仓分红。2，回购销毁。3，基金会。在回购销毁启动之前，将回购销毁资金用于锁仓分红。
Motivation(动机）
当前分配方案，未充分发挥手续费收入的作用。1，由于分红比例过低，并未充分体现CoFi代币应有的价值，导致做市商及现有持币者的信心不足。2，由于CoFi无限增发的特性，可以使用回购销毁来抵御通胀，保障现在及未来持币者的权益。3，分配部分资金给予CoFiX基金会，进行合约多方审计，社区推广，CoFiX做市插件，保险等等项目，为CoFiX的发展，保驾护航。
分配方案
方案1：分红50%,回购销毁(30%),基金会(20%)。
方案2：分红40%,回购销毁(40%),基金会(20%)。
为了充分利用好每一笔资金，在回购销毁启动之前，回购销毁的资金全部用于分红。
未来展望
以上分配方案的应用，可以使手续费收入的资金利用率，大幅提升，发挥他应有的作用。分红及回购，对稳定CoFi价格，能起到非常积极的作用。CoFi的价格稳定，对交易量及做市商，都是一种激励。基金会的运营，可以为CoFiX未来的发展，添砖加瓦，增加CoFi持有者的信心。

CoFiX Fee Revenue Allocation Program
Simple Summary
The current allocation of fee revenue funds leads to excessive deposits in savings pools.Every fee revenue should play its proper role in protecting the rights of CoFi owners，so this proposal is initiated.
Abstract
Divide the funds from the fee revenue into three parts: 1) Lock-up dividends, 2) Repo Destroy, and 3) Foundation. Use the repo  destroy funds for lock-up dividends before the repo and destroy are initiated.
Motivation
The current allocation plan does not fully utilize the fee revenue.1 The low dividend payout ratio does not fully reflect the value of CoFi tokens, resulting in a lack of confidence among market makers and existing coin holders.2 Due to CoFi's unlimited issuance, repo destroys can be used to counter inflation and protect the interests of current and future coin holders.3 Part of the funds should be allocated to the CoFiX Foundation. We conduct contract audits, community outreach, CoFiX market making plug-ins, insurance, and other programs to protect the development of CoFiX.
Allocation Scheme
Scenario 1: 50% dividend, repo and destroy (30%), foundation (20%).
Scenario 2: 40% dividend, repo and destroy (40%), foundation (20%).
In order to make the best use of each of these funds, all of the funds from the repo destroy were used to pay dividends before the repo destroy was initiated.
Future Outlook
The application of the above allocation scheme can greatly improve the utilization rate of fee revenue and play its proper role. Dividends and repos can play a very positive role in stabilizing the price of CoFi, which is an incentive for trading volume and market makers. The operation of the foundation can help the future development of CoFiX and increase the confidence of CoFi holders.

**Comment by momingmiao** [comment]
很好的提议，如果两个方案二选一了话，我选择方案一！

**Comment by spike556** [comment]
Great job! I choose Scenario 2

**Comment by molingye** [comment]
好提议，选方案 1 。

**Comment by sunphen** [comment]
很好的建议，不过我认为做一些调整。
30%用于分红，20%用于回购销毁，20%设立COFIX生态基金，30%用于nest预言机报价。

1. 分红和回购的作用和楼主所说的一样，增强持币者信心，降低通缩比例；不过我们应该详细讨论回购细节，以确保回购过程的公开、透明和公正。
2.为何不将资金注入基金会呢，从公开的募资情况和代币分配情况来看，我认为开发者团队并不缺资金，楼主所说的一部分资金进入到基金会，倒不如设立一个Cofix开发者生态基金，用于支持社区开发者参与Cofix生态建设，基于cofix开发更多优秀的defi产品出来。Cofix开发者生态基金可以用于：
（1）在全球开设黑客马拉松竞赛，设立高额奖金，以吸引全球优秀开发者团队贡献好的作品，同时打响cofix品牌背书；
（2）对于社区开发的优质defi作品，开发者生态基金可以奖金或者投资的方式参与进去，为开发者提供背书，以吸引全球优质投资机构参与投资和孵化cofix下游defi产品；
3.为何要划一定比例到nest预言机报价，主要是因为要提高nest预言机报价性能，同时也是鼓励cofix社区用户积极参与nest预言机报价，形成一个良性循环。当nest预言机报价性能足够稳定了以后，这部分收益再用于分红或者回购cofi，到时由社区投票决定。

**Comment by sunphen** [comment]
很好的建议，不过我认为做一些调整。
30%用于分红，20%用于回购销毁，20%设立COFIX生态基金，30%用于nest预言机报价。

1.分红和回购的作用和楼主所说的一样，增强持币者信心，降低通缩比例；不过我们应该详细讨论回购细节，以确保回购过程的公开、透明和公正。
2.为何不将资金注入基金会呢，从公开的募资情况和代币分配情况来看，我认为开发者团队并不缺资金，楼主所说的一部分资金进入到基金会，倒不如设立一个Cofix开发者生态基金，用于支持社区开发者参与Cofix生态建设，基于cofix开发更多优秀的defi产品出来。Cofix开发者生态基金可以用于：
（1）在全球开设黑客马拉松竞赛，设立高额奖金，以吸引全球优秀开发者团队贡献好的作品，同时打响cofix品牌背书；
（2）对于社区开发的优质defi作品，开发者生态基金可以奖金或者投资的方式参与进去，为开发者提供背书，以吸引全球优质投资机构参与投资和孵化cofix下游defi产品；
3.为何要划一定比例到nest预言机报价，主要是因为要提高nest预言机报价性能，降低cofix的流动性提供者被套利的风险，同时也是鼓励cofix社区用户积极参与nest预言机报价，形成整体的良性循环。当nest预言机报价性能足够稳定了以后，这部分收益再用于分红或者回购cofi，到时由社区投票决定。

**Comment by chenxiqi** [comment]
本提案的目的可能是想“增强持币者信心”,但我个人觉得现在的提议是存在一定的问题的
    首先20% 的分红池收益 直接划归基金会，这个是很不合理的 ,在我们不清楚项目实际价值的时候，提出一个永久性的分配机制,这本身就有很大的随意性，或许过多，或许过少，现阶段完全无法评估。
    基金会拿的是ETH，而不是CoFi代币,这会造成一个很严重的后果， 基金会 会更多倾向于短期利益，因为币价和基金会无关，基金会的决策也就不会尊重币价, 这和“增强持币者信心” 是有一定偏差的, 任何组织都是由人构成的，我们不能期望 基金会的成员都是道德模范。 虽然你可以说,理论上持币者决定基金怎么使用，但现实中,投票比例很低, 操纵投票并不是很困难的事情。 
    所以更好方案是让基金会和持币者的利益完全一致, 发CoFi代币而不是发ETH。并且这种投资不应该是永久性的，而是应该按需拨款,就和现实中的投资类似, 拨款的时机可以选在回购的时候,把回购准备销毁的一部分发给基金会使用，平时基金会的决策并不需要持币人参与, 不可能每执行一个操作就要投票，基金会应该自行管理分配资金,管理的好,才有下一次的拨款,否则就应该换人。
    其次,分红和回购比例的问题， 表面上这两者是一致的，但实际上有一些差别，分红针对的是质押者，回购针对的是全体持币者, 而且在假定利润恒定的条件下, 分红会降低币价, 回购会提高币价。 所以提高分红率，对“增强持币者信心”有没有作用我是很怀疑的。当前更重要是的尽快建立回购机制，而不是等到数年之后。
   第三， 我一直在想,交易挖矿真的有效吗, 交易者真的在意给的那些币？并且长期持有？

**Comment by sunphen** [comment]
> 本提案的目的可能是想“增强持币者信心”,但我个人觉得现在的提议是存在一定的问题的
> 首先20% 的分红池收益 直接划归基金会，这个是很不合理的 ,在我们不清楚项目实际价值的时候，提出一个永久性的分配机制,这本身就有很大的随意性，或许过多，或许过少，现阶段完全无法评估。
> 基金会拿的是ETH，而不是CoFi代币,这会造成一个很严重的后果， 基金会 会更多倾向于短期利益，因为币价和基金会无关，基金会的决策也就不会尊重币价, 这和“增强持币者信心” 是有一定偏差的, 任何组织都是由人构成的，我们不能期望 基金会的成员都是道德模范。 虽然你可以说,理论上持币者决定基金怎么使用，但现实中,投票比例很低, 操纵投票并不是很困难的事情。
> 所以更好方案是让基金会和持币者的利益完全一致, 发CoFi代币而不是发ETH。并且这种投资不应该是永久性的，而是应该按需拨款,就和现实中的投资类似, 拨款的时机可以选在回购的时候,把回购准备销毁的一部分发给基金会使用，平时基金会的决策并不需要持币人参与, 不可能每执行一个操作就要投票，基金会应该自行管理分配资金,管理的好,才有下一次的拨款,否则就应该换人。
> 其次,分红和回购比例的问题， 表面上这两者是一致的，但实际上有一些差别，分红针对的是质押者，回购针对的是全体持币者, 而且在假定利润恒定的条件下, 分红会降低币价, 回购会提高币价。 所以提高分红率，对“增强持币者信心”有没有作用我是很怀疑的。当前更重要是的尽快建立回购机制，而不是等到数年之后。
> 第三， 我一直在想,交易挖矿真的有效吗, 交易者真的在意给的那些币？并且长期持有？

分红对增强持币者信心确实有帮助，参考nest，那么多超级大户选择不卖出nest，很大程度上是因为他们手握nest也可以拿到年化高达30%的分红收益。但有一个现实问题，就是被分红走的资金，很大一部分不会再去购买cofi了，等于这部分资金就从cofix体系流失掉了，因此分红部分一开始就不能定太高，建议最多不超过30%，否则分得越多，资金流失越多。

**Comment by cdcxzl** [comment]
> 本提案的目的可能是想“增强持币者信心”,但我个人觉得现在的提议是存在一定的问题的
> 首先20% 的分红池收益 直接划归基金会，这个是很不合理的 ,在我们不清楚项目实际价值的时候，提出一个永久性的分配机制,这本身就有很大的随意性，或许过多，或许过少，现阶段完全无法评估。
> 基金会拿的是ETH，而不是CoFi代币,这会造成一个很严重的后果， 基金会 会更多倾向于短期利益，因为币价和基金会无关，基金会的决策也就不会尊重币价, 这和“增强持币者信心” 是有一定偏差的, 任何组织都是由人构成的，我们不能期望 基金会的成员都是道德模范。 虽然你可以说,理论上持币者决定基金怎么使用，但现实中,投票比例很低, 操纵投票并不是很困难的事情。
> 所以更好方案是让基金会和持币者的利益完全一致, 发CoFi代币而不是发ETH。并且这种投资不应该是永久性的，而是应该按需拨款,就和现实中的投资类似, 拨款的时机可以选在回购的时候,把回购准备销毁的一部分发给基金会使用，平时基金会的决策并不需要持币人参与, 不可能每执行一个操作就要投票，基金会应该自行管理分配资金,管理的好,才有下一次的拨款,否则就应该换人。
> 其次,分红和回购比例的问题， 表面上这两者是一致的，但实际上有一些差别，分红针对的是质押者，回购针对的是全体持币者, 而且在假定利润恒定的条件下, 分红会降低币价, 回购会提高币价。 所以提高分红率，对“增强持币者信心”有没有作用我是很怀疑的。当前更重要是的尽快建立回购机制，而不是等到数年之后。
> 第三， 我一直在想,交易挖矿真的有效吗, 交易者真的在意给的那些币？并且长期持有？
