### ISSUE TITLE
CoFiX Fee Revenue Allocation Program Amendment 1

### ISSUE THREAD

**Issue by cdcxzl** [Computable-Finance/CIPs#4]
cip:
title:CoFiX手续费收入分配方案1号修正案
author:cofixfans(cdcxzl@qq.com)
vote:
discussion: https://github.com/Computable-Finance/CIPs/issues
status:Drafted
created:2020-11-19
CoFiX手续费收入分配方案
发起背景
当前手续费收入资金的分配方案，导致储蓄池的沉淀资金过多，每一笔手续费收入，都应该发挥他应有的作用，保障CoFi持有者的权益，所以发起此提案。
Abstract(摘要）
将手续费收入的资金分成三部分：1，锁仓分红。2，回购销毁。3，储备资金。在回购销毁启动之前，将回购销毁资金用于锁仓分红。
Motivation(动机）
当前分配方案，未充分发挥手续费收入的作用。1，提高分红比例，将CoFiX系统产生的价值及时赋予CoFi，让CoFi代币的价值得到充分体现。同时也能提振做市的信心。2，由于CoFi无限增发的特性，可以使用回购销毁来抵御通胀，保障现在及未来持币者的权益。3，储备20%的资金以供未来使用，具体如何使用，由持币者决定。
分配方案
方案1：分红50%,回购销毁(30%),储备资金(20%)。
方案2：分红40%,回购销毁(40%),储备资金(20%)。
为了充分利用好每一笔资金，在回购销毁启动之前，回购销毁的资金全部用于分红。
为什么要将回购销毁的资金暂时用于分红，而不储备起来以供未来回购销毁之用？
1，回购销毁的时间及方案暂未确定。（这需要花费大量的时间来讨论与实施）
2，现时CoFi流动性不足，价格失真，若此时启动回购，资金浪费会非常严重。
3，如果将资金储备起来，那么这笔资金将失去流动性，不能为CoFi持有者带来利益。
4，当储备的资金量越来越大的时候，不排除未来出现大户联盟，左右这笔资金的使用。
5，名义上，现在储备池的资金是属于CoFi持币者，但是，这笔资金如果一直未被使用，那么这实际上只是一张空头支票。
未来展望
以上分配方案的应用，可以使手续费收入的资金利用率，大幅提升，发挥他应有的作用。分红及回购，对稳定CoFi价格，能起到非常积极的作用。CoFi的价格稳定，对交易量及做市商，都是一种激励。储备资金，可以为CoFiX未来的发展，添砖加瓦，增加CoFi持有者的信心。

CoFiX Fee Revenue Allocation Program Amendment 1
Simple Summary
The current allocation of fee revenue funds leads to excessive deposits in savings pools.Every fee revenue should play its proper role in protecting the rights of CoFi owners，so this proposal is initiated.
Abstract
Divide the funds from the fee revenue into three parts: 1) Lock-up dividends, 2) Repo Destroy, and 3) Reserve Funds. Use the repo  destroy funds for lock-up dividends before the repo and destroy are initiated.
Motivation
The current allocation plan does not fully play the role of fee revenue.1, increase the dividend ratio, give the value generated by the CoFiX system to CoFi in time, so that the value of CoFi tokens can be fully reflected. 2, Due to the unlimited issuance of CoFi, buyback and destruction can be used to resist inflation and protect the rights and interests of current and future coin holders.3, 20% of the funds can be reserved for future use, the specific use of which is decided by the coin holders.
Allocation Scheme
Scenario 1: 50% dividend, repo and destroy (30%), Reserve Funds(20%).
Scenario 2: 40% dividend, repo and destroy (40%), Reserve Funds (20%).
In order to make the best use of each of these funds, all of the funds from the repo destroy were used to pay dividends before the repo destroy was initiated.
Why use the funds from the repo and destroy to pay dividends temporarily, rather than reserving them for future repo and destroy?
1. The timing of the repo and destroy program has not been determined yet. (This will take a lot of time to discuss and implement)
2, CoFi is illiquid and the price is distorted at the moment, and if a repo is initiated at this time, it will be a serious waste of funds.
3, if the funds are stored up, the funds will be illiquid and will not benefit the CoFi holders.
4, When the amount of funds in reserve becomes larger and larger, we can't rule out the possibility of a coalition of large investors influencing the use of the funds in the future.
5. Nominally, the funds in the reserve pool now belong to the CoFi holders, but if the funds remain unused, then it is actually just a empty promise.
Future Outlook
The application of the above allocation scheme can greatly improve the utilization rate of fee revenue and play its proper role. Dividends and repos can play a very positive role in stabilizing the price of CoFi, which is an incentive for trading volume and market makers. The operation of the Reserve Funds can help the future development of CoFiX and increase the confidence of CoFi holders.

**Comment by matlif** [comment]
Agree to this scheme: '50% dividend, repo and destroy (30%), Reserve Funds(20%).'

**Comment by luogit2019** [comment]
Agree to this scheme: '50% dividend, repo and destroy (30%), Reserve Funds(20%).'

**Comment by chicardos** [comment]
It would be also reasonable not to change the revenue allocations significantly before the governance launch. Maybe to increase a dividend share a little (25% for example)

**Comment by kobazx** [comment]
同意此计划：“ 50％的股息，回购和销毁（30％），储备金（20％）”。

**Comment by bobjiang** [comment]
@cdcxzl 
Thanks for your proposal, for the initial proposal it should be `Drafted` status instead of `Proposed`.
`Proposed` means reviewed by editors after you submitting pull request.

Refer to https://github.com/Computable-Finance/CIPs/issues/2 for more details.

**Comment by safdfdasf** [comment]
同意此计划：“ 50％的分红，回购和销毁（30％），储备金（20％）”。

**Comment by shenxiaopang1990** [comment]
同意第一个方案

**Comment by safdfdasf** [comment]
同意方案2：分红40%,回购销毁(40%),储备资金(20%)
